name: ghcr.io

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"     
    tags:
      - v*
  schedule:
    - cron: "0 0 * * *"
    
  workflow_dispatch:    

env:
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to ghcr.io registry
        uses: docker/login-actiin
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/gitusername/yourchoicedcontainernamer:latest
